"""What the book calls a national team, against what a tipster calls it."""

NATIONS: dict[str, tuple[str, ...]] = {
    # Europe
    "Albánia": ("Albania",),
    "Andorra": ("Andorra",),
    "Anglia": ("England",),
    "Ausztria": ("Austria",),
    "Azerbajdzsán": ("Azerbaijan",),
    "Belgium": ("Belgium",),
    "Bosznia-Hercegovina": ("Bosnia and Herzegovina", "Bosnia"),
    "Bulgária": ("Bulgaria",),
    "Ciprus": ("Cyprus",),
    "Csehország": ("Czechia", "Czech Republic"),
    "Dánia": ("Denmark",),
    "Észak-Írország": ("Northern Ireland",),
    "Észak-Macedónia": ("North Macedonia", "Macedonia"),
    "Észtország": ("Estonia",),
    "Fehéroroszország": ("Belarus",),
    "Feröer-szigetek": ("Faroe Islands",),
    "Finnország": ("Finland",),
    "Franciaország": ("France",),
    "Gibraltár": ("Gibraltar",),
    "Görögország": ("Greece",),
    "Grúzia": ("Georgia",),
    "Hollandia": ("Netherlands", "Holland"),
    "Horvátország": ("Croatia",),
    "Írország": ("Ireland", "Republic of Ireland"),
    "Izland": ("Iceland",),
    "Koszovó": ("Kosovo",),
    "Lengyelország": ("Poland",),
    "Lettország": ("Latvia",),
    "Liechtenstein": ("Liechtenstein",),
    "Litvánia": ("Lithuania",),
    "Luxemburg": ("Luxembourg",),
    "Magyarország": ("Hungary",),
    "Málta": ("Malta",),
    "Moldova": ("Moldova",),
    "Montenegró": ("Montenegro",),
    "Németország": ("Germany",),
    "Norvégia": ("Norway",),
    "Olaszország": ("Italy",),
    "Oroszország": ("Russia",),
    "Örményország": ("Armenia",),
    "Portugália": ("Portugal",),
    "Románia": ("Romania",),
    "San Marino": ("San Marino",),
    "Skócia": ("Scotland",),
    "Spanyolország": ("Spain",),
    "Svájc": ("Switzerland",),
    "Svédország": ("Sweden",),
    "Szerbia": ("Serbia",),
    "Szlovákia": ("Slovakia",),
    "Szlovénia": ("Slovenia",),
    "Törökország": ("Turkey", "Türkiye"),
    "Ukrajna": ("Ukraine",),
    "Wales": ("Wales",),
    # The Americas
    "Antigua és Barbuda": ("Antigua and Barbuda",),
    "Argentína": ("Argentina",),
    "Aruba": ("Aruba",),
    "Bahamák": ("Bahamas",),
    "Barbados": ("Barbados",),
    "Belize": ("Belize",),
    "Bermuda": ("Bermuda",),
    "Bolívia": ("Bolivia",),
    "Brazília": ("Brazil",),
    "Chile": ("Chile",),
    "Costa Rica": ("Costa Rica",),
    "Curaçao": ("Curacao",),
    "Dominikai Közösség": ("Dominica",),
    "Dominikai Köztársaság": ("Dominican Republic",),
    "Ecuador": ("Ecuador",),
    "Egyesült Államok": ("United States", "USA"),
    "El Salvador": ("El Salvador",),
    "Grenada": ("Grenada",),
    "Guatemala": ("Guatemala",),
    "Guyana": ("Guyana",),
    "Haiti": ("Haiti",),
    "Honduras": ("Honduras",),
    "Jamaica": ("Jamaica",),
    "Kanada": ("Canada",),
    "Kolumbia": ("Colombia",),
    "Kuba": ("Cuba",),
    "Mexikó": ("Mexico",),
    "Nicaragua": ("Nicaragua",),
    "Panama": ("Panama",),
    "Paraguay": ("Paraguay",),
    "Peru": ("Peru",),
    "Puerto Rico": ("Puerto Rico",),
    "Saint Kitts és Nevis": ("Saint Kitts and Nevis",),
    "Saint Lucia": ("Saint Lucia",),
    "Suriname": ("Suriname",),
    "Trinidad és Tobago": ("Trinidad and Tobago",),
    "Uruguay": ("Uruguay",),
    "Venezuela": ("Venezuela",),
    # Africa
    "Algéria": ("Algeria",),
    "Angola": ("Angola",),
    "Benin": ("Benin",),
    "Bissau-Guinea": ("Guinea-Bissau",),
    "Botswana": ("Botswana",),
    "Burkina Faso": ("Burkina Faso",),
    "Burundi": ("Burundi",),
    "Csád": ("Chad",),
    "Dél-Afrika": ("South Africa",),
    "Dél-Szudán": ("South Sudan",),
    "Dzsibuti": ("Djibouti",),
    "Egyenlítői-Guinea": ("Equatorial Guinea",),
    "Egyiptom": ("Egypt",),
    "Elefántcsontpart": ("Ivory Coast", "Cote d'Ivoire"),
    "Eritrea": ("Eritrea",),
    "Eswatini": ("Eswatini", "Swaziland"),
    "Etiópia": ("Ethiopia",),
    "Gabon": ("Gabon",),
    "Gambia": ("Gambia",),
    "Ghána": ("Ghana",),
    "Guinea": ("Guinea",),
    "Kamerun": ("Cameroon",),
    "Kenya": ("Kenya",),
    "Komorok": ("Comoros",),
    "Kongói Demokratikus Köztársaság": ("DR Congo", "Congo DR"),
    "Kongói Köztársaság": ("Congo",),
    "Közép-afrikai Köztársaság": ("Central African Republic",),
    "Lesotho": ("Lesotho",),
    "Libéria": ("Liberia",),
    "Líbia": ("Libya",),
    "Madagaszkár": ("Madagascar",),
    "Malawi": ("Malawi",),
    "Mali": ("Mali",),
    "Marokkó": ("Morocco",),
    "Mauritánia": ("Mauritania",),
    "Mauritius": ("Mauritius",),
    "Mozambik": ("Mozambique",),
    "Namíbia": ("Namibia",),
    "Niger": ("Niger",),
    "Nigéria": ("Nigeria",),
    "Ruanda": ("Rwanda",),
    "Seychelle-szigetek": ("Seychelles",),
    "Sierra Leone": ("Sierra Leone",),
    "Szenegál": ("Senegal",),
    "Szomália": ("Somalia",),
    "Szudán": ("Sudan",),
    "Tanzánia": ("Tanzania",),
    "Togo": ("Togo",),
    "Tunézia": ("Tunisia",),
    "Uganda": ("Uganda",),
    "Zambia": ("Zambia",),
    "Zimbabwe": ("Zimbabwe",),
    "Zöld-foki Köztársaság": ("Cape Verde", "Cabo Verde"),
    # Asia and Oceania
    "Afganisztán": ("Afghanistan",),
    "Ausztrália": ("Australia",),
    "Bahrein": ("Bahrain",),
    "Banglades": ("Bangladesh",),
    "Bhután": ("Bhutan",),
    "Brunei": ("Brunei",),
    "Dél-Korea": ("South Korea", "Korea Republic"),
    "Észak-Korea": ("North Korea", "Korea DPR"),
    "Fidzsi-szigetek": ("Fiji",),
    "Fülöp-szigetek": ("Philippines",),
    "Hongkong": ("Hong Kong",),
    "India": ("India",),
    "Indonézia": ("Indonesia",),
    "Irak": ("Iraq",),
    "Irán": ("Iran",),
    "Izrael": ("Israel",),
    "Japán": ("Japan",),
    "Jemen": ("Yemen",),
    "Jordánia": ("Jordan",),
    "Kambodzsa": ("Cambodia",),
    "Katar": ("Qatar",),
    "Kazahsztán": ("Kazakhstan",),
    "Kína": ("China", "China PR"),
    "Kirgizisztán": ("Kyrgyzstan",),
    "Kuvait": ("Kuwait",),
    "Laosz": ("Laos",),
    "Libanon": ("Lebanon",),
    "Makaó": ("Macau",),
    "Malajzia": ("Malaysia",),
    "Maldív-szigetek": ("Maldives",),
    "Mianmar": ("Myanmar",),
    "Mongólia": ("Mongolia",),
    "Nepál": ("Nepal",),
    "Omán": ("Oman",),
    "Pakisztán": ("Pakistan",),
    "Pápua Új-Guinea": ("Papua New Guinea",),
    "Palesztina": ("Palestine",),
    "Szaúd-Arábia": ("Saudi Arabia",),
    "Szingapúr": ("Singapore",),
    "Szíria": ("Syria",),
    "Srí Lanka": ("Sri Lanka",),
    "Tádzsikisztán": ("Tajikistan",),
    "Tajvan": ("Taiwan", "Chinese Taipei"),
    "Thaiföld": ("Thailand",),
    "Törökmenisztán": ("Turkmenistan",),
    "Új-Kaledónia": ("New Caledonia",),
    "Új-Zéland": ("New Zealand",),
    "Üzbegisztán": ("Uzbekistan",),
    "Vietnám": ("Vietnam",),
    "Egyesült Arab Emírségek": ("United Arab Emirates", "UAE"),
}
